pipeline {
  agent any
  options { timestamps() }
  //triggers { cron('H/2 * * * *') } // every ~15 minutes

  stages {
    stage('Send to queue') {
      steps {
        script {
          def jsonText = readFile('every_15m/every_15m.json')
          echo "Sending ${jsonText.length()} bytes from every_15m.json to queue"
          build job: 'optimized/queue',
                wait: false,
                propagate: false,
                parameters: [
                  string(name: 'BATCH_JSON', value: jsonText),
                  string(name: 'SOURCE',     value: 'every_15m')
                ]
        }
      }
    }
  }
}
