pipeline {
  agent any
  parameters {
    string(name: 'PARAM1', defaultValue: '', description: '')
    string(name: 'PARAM2', defaultValue: '', description: '')
    string(name: 'PARAM3', defaultValue: '', description: '')
    string(name: 'PARAM4', defaultValue: '', description: '')
  }
  stages {
    stage('echo params') {
      steps {
        echo "PARAM1=${params.PARAM1}"
        echo "PARAM2=${params.PARAM2}"
        echo "PARAM3=${params.PARAM3}"
        echo "PARAM4=${params.PARAM4}"
      }
    }
  }
}
