pipeline {
  agent any
  options { timestamps() }
  triggers { cron('H/1 * * * *') } // hourly

  stages {
    stage('Send to queue') {
      steps {
        script {
          def jsonText = readFile('hourly/hourly.json')
          echo "Sending ${jsonText.length()} bytes from hourly.json to queue"
          build job: 'optimized/queue',
                wait: false,
                propagate: false,
                parameters: [
                  string(name: 'BATCH_JSON', value: jsonText),
                  string(name: 'SOURCE',     value: 'hourly')
                ]
        }
      }
    }
  }
}
